question_data = [

        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
         "question": "The communication protocol NFC stands for Near-Field Control.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An atom contains a nucleus.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "Liechtenstein does not have an airport.",
                                           "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                                          "question": "According to Greek Mythology, Atlas was an Olympian God.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Kublai Khan is the grandchild of Genghis Khan?", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                           "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]}
]
